

# docker-compose.yml
version: "3.8"

services:
  db:
    image: postgres:9.6
    container_name: medplusdb-api
    restart: always
    environment:
      POSTGRES_USER: medplus
      POSTGRES_PASSWORD: medplus
      POSTGRES_DB: medplus-api
      
    ports:
      - "5445:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data



